name: CodeSpell
permissions:
  contents: read
on:
  - pull_request
jobs:
  codespell:
    name: CodeSpell
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false
      - name: CodeSpell
        uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2.2
        with:
          check_filenames: true
          ignore_words_file: .codespellignore
